#! /bin/sh
### BEGIN INIT INFO
# Provides:          lenovo_image
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: satusmonitor
# Description:       lenovolinux statemonitor
### END INIT INFO

. /lib/lsb/init-functions

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/sbin/lntgr3zservice
NAME=lntgr3zservice
DESC="linux StatusMonitor service"
SCRIPTNAME=/etc/init.d/lntgr3zserviced


case "$1" in
  start)
	log_daemon_msg "Starting $DESC" "$NAME"

	start-stop-daemon --start --quiet --oknodo --exec $DAEMON
	status=$?
	log_end_msg $status
	;;
  stop)
	log_daemon_msg "Stopping $DESC" "$NAME"
	start-stop-daemon --stop --quiet --retry 5 --oknodo --name $NAME
	status=$?
	log_end_msg $status
	;;
  restart)
	log_daemon_msg "Restarting $DESC" "$NAME"
	if start-stop-daemon --stop --quiet --retry 5 --oknodo --name $NAME; then
		start-stop-daemon --start --quiet --exec $DAEMON
	fi
	status=$?
	log_end_msg $status
	;;
  status)
	status_of_proc -p "$DAEMON" "$NAME" && exit 0 || exit $?
	;;
  *)
	echo "Usage: $SCRIPTNAME {start|stop|restart|force-reload|status}" >&2
	exit 3
	;;
esac

exit 0
